services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: revplay_db
      MYSQL_USER: revuser
      MYSQL_PASSWORD: revpass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      # test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "taskuser", "-ptaskpass"]
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prevpass"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/revplay_db
      SPRING_DATASOURCE_USERNAME: revuser
      SPRING_DATASOURCE_PASSWORD: revpass
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mysql_data: